# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: while not true; keep looking;
author: Patrick A. Levell
email: palevell@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  I am an IT guy with 15+ years experience in manufacturing environments.
  Much of that time has been spent working with database applications like J.D. Edwards
  (aka. Oracle EnterpriseOne) that drive management and decision-support systems.
  By the time stuff lands on my desk, it is usually already over time and over budget.
  Said another way, when people come to me, they've already tried cheaper and faster--now,
  they want it better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://palevell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: palevell
github_username:  palevell
linkedin_username: palevell
facebook_username: palevell
google_analytics: UA-153109470-1

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - categories.md
  - resume.md
  - about.md

# Disqus
disqus:
  shortname: palevell

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-cayman
## Available Themes
# jekyll-theme-{architect, cayman, dinky, hacker,
#    leap-day, merlot, midnight, minimal,
#    modernist, slate, tactile, time-machine}
## Theme Scores
## Theme      Score   Comments
## architect    3     Good colour scheme, unprofessional font
## cayman       7     Good color scheme, good font size
## dinky        3     Okay layout, overlapping text in sidebar (my info)
## hacker       4     Too dark, good fonts (and BRIGHT!); need daylight version
## leap-day     2     Ugly colour scheme, header text runs off screen
## merlot       3     Old-fashioned layout, text too small
## midnight     2     Too dark, icky colour scheme, text too small
## minima       5     Bland colour scheme, the ONLY one that has a navigation bar
## minimal      5     Two-column layout, text too small
## modernist    5     Good colour scheme, text too small
## slate        4     Header too dark, text good size
## tactile      4     Gradient-fill background, text good size
## time-machine 4     I like this for code-snippets (ie. gists)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '*~*'

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  # date_format: "%b %-d, %Y"
  date_format: "%A, %B %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: palevell
    github:  palevell
    rss: rss
    # dribbble: jekyll
    facebook: palevell
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: palevell
    # pinterest: jekyll
    # youtube: palevell
    youtube_channel: UC7x54ThSQ-tk_A4i8nXwvkg
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
